### DISCUSSION TITLE
"message": "The command \"'/usr/bin/pdftotext' '/home/domain/public_html/public/cvs/test.pdf' '-'\" failed.\n\nExit Code: 127(Command not found)\n\nWorking directory: /home/domain/public_html\n\nOutput:\n================\n\n\nError Output:\n================\nsh: /usr/bin/pdftotext: No such file or directory\n",

### DISCUSSION THREAD

**Discussion by dharshini19696** [spatie/pdf-to-text#62] [Q&A]
Could you help me with this?

**Comment by alphaolomi** [comment]
Pass the `$binPath` manually 

On macOS, if you installed using `brew install poppler`
the binPath is `/usr/local/bin/pdftotext` 

```php
use Spatie\PdfToText\Pdf;

$binPath = '/usr/local/bin/pdftotext';

$text = (new Pdf($binPath))
        ->setPdf('sample.pdf')
        // ->setTimeout(60) 60 is the default
        ->text();
```

**Comment by tonsoflaz2** [comment]
This solution doesn't work for me... here is my code:
```
$pdf_extractor = new Pdf('/usr/local/bin/pdftotext');
            //dd($pdf_extractor);
            $text = $pdf_extractor->getText($tempPdfPath);
```
Here is the error:
```
 Spatie\PdfToText\Exceptions\CouldNotExtractText 

  The command "'/usr/bin/pdftotext' '/Users/fluency/Downloads/test.pdf' '-'" failed.

Exit Code: 126(Invoked command cannot execute)

Working directory: /Users/fluency/Code/ahai

Output:
================


Error Output:
================
sh: /usr/bin/pdftotext: No such file or directory
sh: line 0: exec: /usr/bin/pdftotext: cannot execute: No such file or directory

```

It doesnt seem to respect the new path. Any idea why not, or what I could try?
Thank you in advance

**Comment by lucenarenato** [comment]
alguém resolveu?

**Reply by AlbertAlfaro** [reply]
https://github.com/spatie/pdf-to-text/discussions/62#discussioncomment-6833227

**Comment by AlbertAlfaro** [comment]
In macOS the binPath is '/opt/homebrew/bin/pdftotext'


`$binPath = '/opt/homebrew/bin/pdftotext';
$path =storage_path().'/pdf/test.pdf';
$text = (new Pdf($binPath))
        ->setPdf($path)
        ->text();

return $text;`


You can verify if the binary is installed on your system by issuing this command:

which pdftotext

**Comment by EliasPereirah** [comment]
Check if you have already followed these steps: https://github.com/spatie/pdf-to-text#requirements
On Linux I solved it simply by using: apt-get install poppler-utils

**Comment by sultanos** [comment]
I have the same problem , and i am using Docker , might this be the cause to it , and if so , how can i change docker-compose.yml to solve this .
```
version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: your_mysql_root_password

volumes:
  db_data:
```
or i think it could be that i am on a windows enviroment running my docker , god knows
